site_name: FujiHack
site_url: https://fujihack.github.io
site_description: FujiHack Docs
site_author: FujiHack Contributors

repo_url: https://github.com/fujihack/wiki
edit_uri: ""

theme:
    name: readthedocs
    locale: en
    highlightjs: true
    hljs_languages:
        - yaml
        - django

nav:
    - Discord: https://discord.gg/UZXDktvAZP
    - Online Firmware Patcher: https://fujihack.github.io/patcher/
    - Internals:
        - Fuji OS: fujirtos.md
        - Key list: keys.md
        - AUTO ACT Script: autoactscr.md
        - Tasks: tasks.md
    - FujiHack:
        - Project Structure: structure.md 
        - Help Needed: todo.md
    - About:
        - Contributing: about/contributing.md
        - License: about/license.md
