site_name: FujiHack Wiki
site_url: https://fujihack.github.io/
site_description: Wiki for Fujihack, holding all information about the project
site_author: FujiHack Contributors

repo_url: https://github.com/fujihack/fujihack.github.io
edit_uri: ""

theme:
    name: mkdocs
    locale: en
    highlightjs: true
    hljs_languages:
        - c

extra_css:
    - a.css

nav:
    - Online Firmware Patcher: https://fujihack.github.io/patcher/
    - Internals:
        - RTOS: fujirtos.md
        - Key codes: keys.md
        - AUTO ACT script: autoactscr.md
        - Tasks: tasks.md
        - PTP/USB: ptp.md
        - Syslog: syslog.md
        - Function signatures: signatures.md
    - Development:
        - Vocabulary: words.md
        - Project Structure: structure.md 
        - Help Needed: todo.md
